import React,{useEffect,useRef,useState}from"react";
const CV="https://docs.opencv.org/4.x/opencv.js",ROI=.04;
const med=a=>{a=[...a].sort((x,y)=>x-y);let i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
export default function App(){
 const v=useRef(),out=useRef(),work=useRef(),stream=useRef(),bg=useRef(),typ=useRef(0),hist=useRef([]),last=useRef(0),raf=useRef();
 const[ready,setReady]=useState(false),[cams,setCams]=useState([]),[cam,setCam]=useState(''),[count,setCount]=useState(0),[status,setStatus]=useState('Carregando OpenCV...'),[bgok,setBgok]=useState(false),[objok,setObjok]=useState(false),[area,setArea]=useState(0),[thr,setThr]=useState(32),[min,setMin]=useState(25),[sep,setSep]=useState(42),[overlay,setOverlay]=useState(true),[run,setRun]=useState(true),[cal,setCal]=useState(false),[warn,setWarn]=useState('');
 useEffect(()=>{let t;let s=document.createElement('script');if(!window.cv&&!document.querySelector(`script[src="${CV}"]`)){s.src=CV;s.async=true;document.body.appendChild(s)}t=setInterval(async()=>{try{if(window.cv){if(window.cv instanceof Promise)window.cv=await window.cv;if(window.cv.Mat){setReady(true);setStatus('OpenCV pronto');clearInterval(t)}}}catch{}},200);return()=>clearInterval(t)},[]);
 const stop=()=>{stream.current?.getTracks().forEach(x=>x.stop());stream.current=null};
 const list=async()=>{try{let p=await navigator.mediaDevices.getUserMedia({video:true});p.getTracks().forEach(x=>x.stop());let d=(await navigator.mediaDevices.enumerateDevices()).filter(x=>x.kind==='videoinput');setCams(d);if(!cam&&d[0])setCam(d[0].deviceId)}catch{setStatus('Autorize a câmera no Chrome')}};
 useEffect(()=>{list();return()=>stop()},[]);
 useEffect(()=>{if(!cam)return;(async()=>{try{stop();let s=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:cam},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30}}});stream.current=s;v.current.srcObject=s;await v.current.play();bg.current?.delete();bg.current=null;typ.current=0;hist.current=[];setBgok(false);setObjok(false);setCount(0);setStatus('Câmera ativa • calibre o fundo vazio')}catch{setStatus('Não foi possível abrir a câmera')}})()},[cam]);
 const frame=()=>{if(!v.current||v.current.readyState<2||!v.current.videoWidth)return null;let w=Math.min(1280,v.current.videoWidth),h=Math.round(w*v.current.videoHeight/v.current.videoWidth),c=work.current;c.width=w;c.height=h;c.getContext('2d',{willReadFrequently:true}).drawImage(v.current,0,0,w,h);return window.cv.imread(c)};
 const rect=m=>new window.cv.Rect(Math.round(m.cols*ROI),Math.round(m.rows*ROI),Math.round(m.cols*(1-2*ROI)),Math.round(m.rows*(1-2*ROI)));
 const gray=f=>{let cv=window.cv,r=rect(f),s=f.roi(r),g=new cv.Mat(),b=new cv.Mat();cv.cvtColor(s,g,cv.COLOR_RGBA2GRAY);cv.GaussianBlur(g,b,new cv.Size(3,3),0);s.delete();g.delete();return b};
 const mask=f=>{if(!bg.current)return null;let cv=window.cv,g=gray(f),d=new cv.Mat(),m=new cv.Mat();if(g.rows!==bg.current.rows){g.delete();d.delete();m.delete();return null}cv.absdiff(g,bg.current,d);cv.threshold(d,m,thr,255,cv.THRESH_BINARY);let k=cv.getStructuringElement(cv.MORPH_ELLIPSE,new cv.Size(3,3));cv.morphologyEx(m,m,cv.MORPH_OPEN,k);cv.morphologyEx(m,m,cv.MORPH_CLOSE,k);k.delete();g.delete();d.delete();return m};
 const comp=m=>{let cv=window.cv,l=new cv.Mat(),s=new cv.Mat(),c=new cv.Mat(),n=cv.connectedComponentsWithStats(m,l,s,c,8,cv.CV_32S);return{n,l,s,c}};
 const calBg=async()=>{if(!ready||cal)return;setCal(true);setStatus('Capturando fundo...');let cv=window.cv,a=null,n=0;try{for(let i=0;i<16;i++){await new Promise(r=>setTimeout(r,65));let f=frame();if(!f)continue;let g=gray(f),x=new cv.Mat();g.convertTo(x,cv.CV_32F);if(!a)a=cv.Mat.zeros(x.rows,x.cols,cv.CV_32F);cv.add(a,x,a);n++;x.delete();g.delete();f.delete()}if(n<5)throw Error('frames insuficientes');a.convertTo(a,cv.CV_32F,1/n);let b=new cv.Mat();a.convertTo(b,cv.CV_8U);a.delete();bg.current?.delete();bg.current=b;typ.current=0;hist.current=[];setBgok(true);setObjok(false);setArea(0);setStatus('Fundo pronto • coloque 5–30 grãos separados')}catch(e){setStatus('Falha: '+e.message)}setCal(false)};
 const calObj=()=>{let f=frame();if(!f)return;let m=mask(f);if(!m){f.delete();return}let cv=window.cv,q=comp(m),a=[];for(let i=1;i<q.n;i++){let z=q.s.intAt(i,cv.CC_STAT_AREA);if(z>=min&&z<m.rows*m.cols*.02)a.push(z)}q.l.delete();q.s.delete();q.c.delete();m.delete();f.delete();if(a.length<3){setStatus('Mostre pelo menos 3 grãos separados');return}let z=med(a);typ.current=z;hist.current=[];setArea(Math.round(z));setObjok(true);setStatus('Calibrado • contagem ativa')};
 const detect=m=>{let cv=window.cv,q=comp(m),o=[],t=typ.current||Math.max(min*3,1);for(let i=1;i<q.n;i++){let a=q.s.intAt(i,cv.CC_STAT_AREA);if(a<min)continue;let x=q.s.intAt(i,cv.CC_STAT_LEFT),y=q.s.intAt(i,cv.CC_STAT_TOP),w=q.s.intAt(i,cv.CC_STAT_WIDTH),h=q.s.intAt(i,cv.CC_STAT_HEIGHT),cx=q.c.doubleAt(i,0),cy=q.c.doubleAt(i,1),units=1;if(typ.current&&a>=t*1.55){let lm=m.roi(new cv.Rect(x,y,w,h)),d=new cv.Mat(),p=new cv.Mat(),mk=new cv.Mat();cv.distanceTransform(lm,d,cv.DIST_L2,3);let mm=cv.minMaxLoc(d);cv.threshold(d,p,mm.maxVal*sep/100,255,cv.THRESH_BINARY);p.convertTo(p,cv.CV_8U);let seeds=cv.connectedComponents(p,mk,8,cv.CV_32S)-1;units=Math.max(seeds,Math.max(1,Math.round(a/t)));units=Math.min(units,Math.max(1,Math.ceil(a/Math.max(min,t*.35))));lm.delete();d.delete();p.delete();mk.delete()}o.push({x:cx,y:cy,units})}q.l.delete();q.s.delete();q.c.delete();return o};
 const stable=x=>{let h=hist.current;h.push(x);if(h.length>9)h.shift();if(h.length<4)return x;let f={};h.forEach(v=>f[v]=(f[v]||0)+1);let b=Object.entries(f).sort((a,b)=>b[1]-a[1])[0];return b[1]>=4?+b[0]:Math.round(med(h))};
 const render=(f,m,o)=>{let cv=window.cv,z=f.clone(),r=rect(f),view=z.roi(r);if(overlay){let pink=new cv.Mat(view.rows,view.cols,view.type(),new cv.Scalar(255,20,147,255)),blend=new cv.Mat();cv.addWeighted(view,.55,pink,.45,0,blend);blend.copyTo(view,m);o.forEach(a=>cv.circle(view,new cv.Point(Math.round(a.x),Math.round(a.y)),2,new cv.Scalar(255,255,255,255),-1));pink.delete();blend.delete()}cv.rectangle(z,new cv.Point(r.x,r.y),new cv.Point(r.x+r.width,r.y+r.height),new cv.Scalar(255,20,147,255),2);cv.imshow(out.current,z);view.delete();z.delete()};
 useEffect(()=>{if(!ready)return;let loop=now=>{raf.current=requestAnimationFrame(loop);if(!run||now-last.current<140)return;last.current=now;let f=frame();if(!f)return;try{if(!bg.current){window.cv.imshow(out.current,f);return}let m=mask(f);if(!m)return;let o=detect(m),raw=o.reduce((s,a)=>s+a.units,0),n=stable(raw);setCount(n);setWarn(raw!==n?`Estabilizando • instantâneo ${raw.toLocaleString('pt-BR')}`:'');render(f,m,o);m.delete()}catch(e){console.error(e);setWarn('Falha em um frame; continuando')}finally{f.delete()}};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[ready,run,thr,min,sep,overlay]);
 return <div className="app"><canvas ref={work} hidden/><header><div><h1>Contador de Grãos Web</h1><p>Webcam + OpenCV.js • sem Python • processamento local</p></div><b className={ready?'ok':'wait'}>{ready?'OpenCV pronto':'Carregando...'}</b></header><main><section className="camera"><div className="stage"><video ref={v} autoPlay playsInline muted/><canvas ref={out}/></div><div className="bar"><select value={cam} onChange={e=>setCam(e.target.value)}>{cams.map((d,i)=><option key={d.deviceId} value={d.deviceId}>{d.label||`Câmera ${i+1}`}</option>)}</select><button onClick={list}>Atualizar câmeras</button><button onClick={()=>setRun(x=>!x)}>{run?'Pausar':'Continuar'}</button></div></section><aside><div className="card center"><small>CONTAGEM</small><div className="number">{count.toLocaleString('pt-BR')}</div><div className={objok?'msg ok':'msg wait'}>{status}</div>{warn&&<p className="warn">{warn}</p>}</div><div className="card"><h3>Calibração pela webcam</h3><p>1. Deixe a superfície vazia. 2. Depois coloque 5–30 grãos separados.</p><button className="pink" disabled={!ready||cal||!stream.current} onClick={calBg}>{cal?'CAPTURANDO...':'1. CALIBRAR FUNDO'}</button><button disabled={!bgok} onClick={calObj}>2. CALIBRAR OBJETOS</button>{area>0&&<p className="ok">Área típica: {area} px²</p>}</div><div className="card"><h3>Ajustes</h3><label>Sensibilidade: {thr}<input type="range" min="8" max="100" value={thr} onChange={e=>setThr(+e.target.value)}/></label><label>Área mínima: {min}<input type="range" min="5" max="600" value={min} onChange={e=>setMin(+e.target.value)}/></label><label>Separação: {sep}%<input type="range" min="15" max="75" value={sep} onChange={e=>setSep(+e.target.value)}/></label><label><input type="checkbox" checked={overlay} onChange={e=>setOverlay(e.target.checked)}/> Pintar objetos em rosa</label></div></aside></main></div>
}
